console.log('=== AUTHENTICATION DEBUG ===');
console.log('This script helps debug the authentication issue.');
console.log('');
console.log('Steps to debug:');
console.log('1. Open browser Developer Tools (F12)');
console.log('2. Go to Application/Storage tab');
console.log('3. Check Cookies for this domain');
console.log('4. Look for "admin-token" cookie');
console.log('5. If found, delete it and reload the page');
console.log('');
console.log('Expected behavior after clearing admin-token:');
console.log('- User "abby" should show as AUTHOR role');
console.log('- Should NOT see USERS menu');
console.log('- Should NOT be able to manage all categories');
console.log('');
console.log('If issue persists, check:');
console.log('- /api/auth/user-info endpoint response');
console.log('- Firebase authentication state');
console.log('- Browser localStorage/sessionStorage');